services:
  development:
    build:
      context: .
      target: development
    ports:
      - "3300:3300"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    command: npm run dev

  production:
    build:
      context: .
      target: production  
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=production
    volumes:
      - type: bind
        source: ./public/audio
        target: /app/public/audio
        read_only: true
    restart: unless-stopped




