import type { Metadata } from "next";
import "./globals.css";
import { Button } from "@/shared/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-[var(--foreground)] overflow-hidden flex flex-col">
        <nav className="h-28 flex justify-center items-center">
          <div className="flex gap-4">
            <Button>Warhammer 40k</Button>
            <Button>Warhammer Age Of Sigmar</Button>
            <Button>Warhammer Old World</Button>
            <Button>Все остальное</Button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
