import type { Metadata } from "next";
import Header from "@/wigets/header/Header";
import { Cormorant } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cormorant = Cormorant({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cormorant.className}>
      <body className="h-screen flex flex-col bg-[var(--foreground)] overflow-hidden ">
        <Header />
        {children}
      </body>
    </html>
  );
}
